# Generated by Django 5.1.4 on 2024-12-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.TextField(default='real estate Sierra Leone, top realtors in Sierra Leone, luxury homes Freetown, land for sale Sierra Leone, beachfront properties Sierra Leone, commercial real estate Freetown, rent homes Sierra Leone, property investment Sierra Leone, trusted real estate agency, affordable housing Sierra Leone, buy property Freetown')),
                ('description', models.TextField(default="Global Salone is your trusted global partner for premium real estate services in Sierra Leone. Whether you're buying, selling, or renting luxury homes, commercial spaces, or land, we deliver unparalleled expertise to help you secure your dream property. Start your property journey today.")),
                ('author', models.CharField(default='Global Salone Real Estate', max_length=255)),
                ('language', models.CharField(default='en', max_length=50)),
                ('schema_json', models.JSONField(default=dict)),
                ('og_title', models.CharField(default='Global Salone | Real Estate in Sierra Leone', max_length=255)),
                ('og_description', models.TextField(default='Searching for top-tier real estate services in Sierra Leone? Global Salone offers luxury homes, beachfront estates, commercial spaces, and land investment opportunities. With expertise in property buying, selling, and renting, we help you find your dream property today.')),
                ('og_image', models.URLField(default='https://globalsalone.com/images/featured-property.jpg')),
                ('twitter_title', models.CharField(default='Global Salone | Real Estate in Sierra Leone', max_length=255)),
                ('twitter_description', models.TextField(default='Discover the finest real estate in Sierra Leone with Global Salone. From luxury homes to beachfront estates, we offer premium properties for sale and rent. Start your global property journey today.')),
                ('twitter_image', models.URLField(default='https://globalsalone.com/images/featured-property.jpg')),
                ('canonical_url', models.URLField(default='https://globalsalone.com/')),
            ],
        ),
    ]
