# Generated by Django 5.1.4 on 2024-12-16 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seosettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceitem',
            name='button_text',
            field=models.CharField(max_length=50),
        ),
    ]
