# Generated by Django 5.1.4 on 2024-12-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_serviceitem_button_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceitem',
            name='button_text',
            field=models.CharField(default='Read More', max_length=50),
        ),
    ]
